import { isDevMode } from '@angular/core';

const SERVER_BASE_URL_DEVELOPMENT = 'https://localhost:7048';
const SERVER_BASE_URL_PRODUCTION = '';

const BASE_ENDPOINTS = {
  GET_ALL_USERS: 'users',
};

const DEVELOPMENT_ENDPOINTS = {
    GET_ALL_USERS: `${SERVER_BASE_URL_DEVELOPMENT}/${BASE_ENDPOINTS.GET_ALL_USERS}`,
};

const PRODUCTION_ENDPOINTS = {
    GET_ALL_USERS: `${SERVER_BASE_URL_PRODUCTION}/${BASE_ENDPOINTS.GET_ALL_USERS}`,
};

const ENDPOINTS_TO_EXPORT = isDevMode() ? DEVELOPMENT_ENDPOINTS : PRODUCTION_ENDPOINTS;

export default ENDPOINTS_TO_EXPORT;
