// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserDirectory.Data.SqlServer;

#nullable disable

namespace UserDirectory.Data.SqlServer.Migrations
{
    [DbContext(typeof(Storage))]
    [Migration("20221115153718_AddDateOfBirth")]
    partial class AddDateOfBirth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserDirectory.Domain.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "76 Sherman Road",
                            City = "Hastings",
                            Country = "Aruba",
                            DateOfBirth = "31 Mar 1980",
                            EmailAddress = "emma.dunham@vtgrafix.gov",
                            FirstName = "Emma",
                            LastName = "Dunham",
                            ZipCode = "06830"
                        },
                        new
                        {
                            Id = 2,
                            Address = "18 Hartswood Road",
                            City = "Stanford",
                            Country = "Algeria",
                            DateOfBirth = "09 Aug 1958",
                            EmailAddress = "ivan.risley@nitrosystems.co",
                            FirstName = "Ivan",
                            LastName = "Risley",
                            ZipCode = "04346"
                        },
                        new
                        {
                            Id = 3,
                            Address = "56 Canal Street",
                            City = "London",
                            Country = "Iceland",
                            DateOfBirth = "18 Sep 1963",
                            EmailAddress = "rikki.paquette@anaplex.xyz",
                            FirstName = "Rikki",
                            LastName = "Paquette",
                            ZipCode = "16935"
                        },
                        new
                        {
                            Id = 4,
                            Address = "55 Wooster Road",
                            City = "Adelaide",
                            Country = "Eritrea",
                            DateOfBirth = "14 Aug 1979",
                            EmailAddress = "roman.bourne@baramax.co",
                            FirstName = "Roman",
                            LastName = "Bourne",
                            ZipCode = "46446"
                        },
                        new
                        {
                            Id = 5,
                            Address = "31 Bramble Lane",
                            City = "Auckland",
                            Country = "Netherlands",
                            DateOfBirth = "12 May 1955",
                            EmailAddress = "lyn.chapman@loopsys.xyz",
                            FirstName = "Lyn",
                            LastName = "Chapman",
                            ZipCode = "45893"
                        },
                        new
                        {
                            Id = 6,
                            Address = "42 Walford Way",
                            City = "Beaverton",
                            Country = "France",
                            DateOfBirth = "15 Feb 1981",
                            EmailAddress = "rosie.finn@sealine.co",
                            FirstName = "Rosie",
                            LastName = "Finn",
                            ZipCode = "10697"
                        },
                        new
                        {
                            Id = 7,
                            Address = "38 Colwood Place",
                            City = "Wilmington",
                            Country = "Guatemala",
                            DateOfBirth = "18 May 1956",
                            EmailAddress = "cedric.webster@solexis.co",
                            FirstName = "Cedric",
                            LastName = "Webster",
                            ZipCode = "01521"
                        },
                        new
                        {
                            Id = 8,
                            Address = "50 Hunt Street",
                            City = "Cardiff",
                            Country = "Tanzania, United Republic of",
                            DateOfBirth = "16 Jan 1989",
                            EmailAddress = "rosanne.starck@dalserve.org",
                            FirstName = "Rosanne",
                            LastName = "Starck",
                            ZipCode = "65339"
                        },
                        new
                        {
                            Id = 9,
                            Address = "22 Clarendon Street",
                            City = "Portsmouth",
                            Country = "Guernsey",
                            DateOfBirth = "14 Aug 1976",
                            EmailAddress = "emma.young@terralabs.info",
                            FirstName = "Emma",
                            LastName = "Young",
                            ZipCode = "02285"
                        },
                        new
                        {
                            Id = 10,
                            Address = "85 Golden Lane",
                            City = "Medford",
                            Country = "Nigeria",
                            DateOfBirth = "22 Sep 1953",
                            EmailAddress = "stan.milling@corerobotics.gov",
                            FirstName = "Stan",
                            LastName = "Milling",
                            ZipCode = "29916"
                        },
                        new
                        {
                            Id = 11,
                            Address = "50 Mount Street",
                            City = "Woodville",
                            Country = "Puerto Rico",
                            DateOfBirth = "16 May 1985",
                            EmailAddress = "jenette.oldman@hivemind.biz",
                            FirstName = "Jenette",
                            LastName = "Oldman",
                            ZipCode = "47870"
                        },
                        new
                        {
                            Id = 12,
                            Address = "30 Buckley Street",
                            City = "Tacoma",
                            Country = "Latvia",
                            DateOfBirth = "13 Dec 1954",
                            EmailAddress = "max.hyder@polycore.gov",
                            FirstName = "Max",
                            LastName = "Hyder",
                            ZipCode = "73729"
                        },
                        new
                        {
                            Id = 13,
                            Address = "26 Mercer Street",
                            City = "Hobart",
                            Country = "Hong Kong",
                            DateOfBirth = "03 Jan 1982",
                            EmailAddress = "juliana.kelsey@grafixmedia.xyz",
                            FirstName = "Juliana",
                            LastName = "Kelsey",
                            ZipCode = "98550"
                        },
                        new
                        {
                            Id = 14,
                            Address = "64 Bramble Lane",
                            City = "Adelaide",
                            Country = "Malta",
                            DateOfBirth = "06 Aug 1985",
                            EmailAddress = "adam.hollis@triosys.co",
                            FirstName = "Adam",
                            LastName = "Hollis",
                            ZipCode = "50998"
                        },
                        new
                        {
                            Id = 15,
                            Address = "52 Orchard Road",
                            City = "Boston",
                            Country = "Norfolk Island",
                            DateOfBirth = "12 Sep 1971",
                            EmailAddress = "alexis.brandt@terralabs.gov",
                            FirstName = "Alexis",
                            LastName = "Brandt",
                            ZipCode = "56707"
                        },
                        new
                        {
                            Id = 16,
                            Address = "42 Glenn Drive",
                            City = "Toledo",
                            Country = "Nicaragua",
                            DateOfBirth = "12 Mar 1955",
                            EmailAddress = "travis.cappel@ulogica.gov",
                            FirstName = "Travis",
                            LastName = "Cappel",
                            ZipCode = "54985"
                        },
                        new
                        {
                            Id = 17,
                            Address = "89 Rivington Street",
                            City = "Lancaster",
                            Country = "Congo",
                            DateOfBirth = "18 May 1976",
                            EmailAddress = "layla.flinn@seelogic.club",
                            FirstName = "Layla",
                            LastName = "Flinn",
                            ZipCode = "40390"
                        },
                        new
                        {
                            Id = 18,
                            Address = "87 Coleman Avenue",
                            City = "Durham",
                            Country = "Guyana",
                            DateOfBirth = "03 Sep 1968",
                            EmailAddress = "raylene.sager@infratouch.net",
                            FirstName = "Raylene",
                            LastName = "Sager",
                            ZipCode = "85733"
                        },
                        new
                        {
                            Id = 19,
                            Address = "73 Robinson Street",
                            City = "Wilmington",
                            Country = "Zambia",
                            DateOfBirth = "13 Sep 1989",
                            EmailAddress = "chloe.turner@playtech.mobi",
                            FirstName = "Chloe",
                            LastName = "Turner",
                            ZipCode = "82963"
                        },
                        new
                        {
                            Id = 20,
                            Address = "45 Windsor Avenue",
                            City = "Sheffield",
                            Country = "Zimbabwe",
                            DateOfBirth = "24 Jan 1978",
                            EmailAddress = "roman.porras@mediadime.xyz",
                            FirstName = "Roman",
                            LastName = "Porras",
                            ZipCode = "05706"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
